initGallerySlideshow({
	imageDir: "Recent/",
	images: [
		"../bloom.jpg",
		"../maxibloom.jpg",
		"Kurt2025.jpg",
		"9thwonder.jpg",
		"A New complaint.jpg",
		"A time on art.jpg",
		"AWONT.jpg",
		"B-127.jpg",
		"Beffect.jpg",
		"better version2.jpg",
		"BGround.jpg",
		"BLincolour.jpg",
		"bonzai.jpg",
		"BooBo.jpg",
		"brokenHGlass.jpg",
		"colour.jpg",
		"cosmic inspiration.jpg",
		"cosmicdrag.jpg",
		"Dali.jpg",
		"Dark Rose.jpg",
		"darkbeliever.jpg",
		"Delorean23.jpg",
		"dragon.jpg",
		"dragon1.jpg",
		"dragon2.jpg",
		"DSpidey.jpg",
		"ed209.jpg",
		"edgeway2.jpg",
		"fearless.jpg",
		"freebird.jpg",
		"globejack.jpg",
		"GROGU.jpg",
		"Guitar.jpg",
		"ho.jpg",
		"hopecolours2one.jpg",
		"joe.jpg",
		"kida.jpg",
		"Korn Box.jpg",
		"KOWT.jpg",
		"LIAB.jpg",
		"lonewolf.jpg",
		"magicmikey.jpg",
		"MHBM.jpg",
		"mikey.jpg",
		"Milky way.jpg",
		"MMikey.jpg",
		"my hometown.jpg",
		"N.jpg",
		"neon1.jpg",
		"Noise.jpg",
		"One love.jpg",
		"otherside.jpg",
		"owl.jpg",
		"parislost.jpg",
		"peace when youre done.jpg",
		"phoenix.jpg",
		"Portrait of time.jpg",
		"R2D.jpg",
		"rewire.jpg",
		"RIP.jpg",
		"Roar.jpg",
		"S2.jpg",
		"Scorpion.jpg",
		"she has the power.jpg",
		"Slightly Jimi.jpg",
		"SMMikey.jpg",
		"staircase.jpg",
		"stareyeye3(1).jpg",
		"starstruck.jpg",
		"TollymoreGrootB.jpg",
		"trustit.jpg",
		"turtles.jpg",
		"VGROOT.jpg",
		"waterdragon.jpg",
		"waterfox.jpg",
		"WTF Jimi.jpg",
		"XING.jpg",
		"YODA.jpg",
		"zerojack2.jpg",
		"zzzAubrey.jpg"
	],
	galleryNav: {
		prev: { href: "tattoos.html?start=colourbannerscan.jpg", label: "Tattoos" },
		next: { href: "vectors.html?start=marios.jpg", label: "Vectors" }
	}
});
