initGallerySlideshow({
	imageDir: "vectors/",
	images: [
		"marios.jpg",
		"alien.jpg",
		"Angel.jpg",
		"balloon-dog2.jpg",
		"Beetlejuice.jpg",
		"bluebutterbloss.jpg",
		"bluebutterfly.jpg",
		"bluedragon.jpg",
		"blueflower.jpg",
		"Bluejay_dragon.jpg",
		"brush.jpg",
		"carol1.jpg",
		"carol2.jpg",
		"delorean.jpg",
		"deloreanback.jpg",
		"deloreanfront.jpg",
		"Doc-Brown.jpg",
		"fireplace.jpg",
		"ghosthouse.jpg",
		"giz.jpg",
		"gizbo.jpg",
		"grendelsmother.jpg",
		"heath2.jpg",
		"jack.jpg",
		"jeffhardy.jpg",
		"kalisie-dragon.jpg",
		"kat-kat-von-d.jpg",
		"klopecks.jpg",
		"Kratos.jpg",
		"Kratos2.jpg",
		"logovector.jpg",
		"paul.jpg",
		"pinkbutterfly.jpg",
		"predator.jpg",
		"pumpkin.jpg",
		"santa_hat.jpg",
		"sexyicon.jpg",
		"skull.jpg",
		"skullbed.jpg",
		"spooky tree & bats copy.jpg",
		"witchblade.jpg",
		"yellow butterfly.jpg"
	],
	galleryNav: {
		prev: { href: "latest.html?start=Kurt2025.jpg", label: "Latest" },
		next: { href: "portraits.html?start=Megan.jpg", label: "Pencil Drawings" }
	}
});
